import uuid
from datetime import datetime, timezone
from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, Index, String
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from src.models.base import Base, UUIDPrimaryKeyMixin, TimestampMixin


class Device(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Represents an authorized MT5 Connector client device bound to an Exness account
    and scoped to a specific Tenant.
    """
    __tablename__ = "devices"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    device_secret_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    # Stored plaintext or encrypted with backend master key for HMAC verification
    device_secret: Mapped[str] = mapped_column(String(64), nullable=False)
    
    # 5-Tuple Broker Identity Binding
    broker: Mapped[str] = mapped_column(String(50), default="EXNESS", nullable=False)
    account_number: Mapped[int] = mapped_column(BigInteger, nullable=False, index=True)
    server_name: Mapped[str] = mapped_column(String(100), nullable=False)
    trade_mode: Mapped[str] = mapped_column(String(20), nullable=False)  # REAL or DEMO
    currency: Mapped[str] = mapped_column(String(10), nullable=False)

    terminal_build: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)
    connector_version: Mapped[str] = mapped_column(String(20), default="1.0.0", nullable=False)
    
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_revoked: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    last_sync_time_msc: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)
    last_sync_deal_ticket: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)

    # Relationships
    tenant = relationship("Tenant", backref="devices")

    __table_args__ = (
        Index("ix_devices_tenant_account", "tenant_id", "account_number"),
    )


class PairingToken(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Single-use, short-lived (5-min) token generated by Web Dashboard
    for initializing connector pairing handshakes.
    """
    __tablename__ = "pairing_tokens"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    token_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    is_used: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    tenant = relationship("Tenant")
    user = relationship("User")
