"""phase4_raw_ingress_and_sync_state

Revision ID: 2141b1a8b66a
Revises: ad084bfbed4b
Create Date: 2026-08-18 20:31:52.147151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2141b1a8b66a'
down_revision: Union[str, None] = 'ad084bfbed4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_sync_states',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('trade_mode', sa.String(length=10), nullable=False),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('current_cursor_time_msc', sa.BigInteger(), nullable=False),
    sa.Column('current_cursor_deal_ticket', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_device_id', sa.UUID(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_batch_idx', sa.Integer(), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_anomalies_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['last_synced_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'broker', 'account_number', 'server_name', name='uq_account_sync_4tuple')
    )
    with op.batch_alter_table('account_sync_states', schema=None) as batch_op:
        batch_op.create_index('idx_account_sync_lookup', ['tenant_id', 'broker', 'account_number', 'server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_sync_states_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_sync_states_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('raw_ingress_payloads',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('payload_type', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_ingress_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_ingress_payloads_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_ingress_payloads_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_ingress_payloads_payload_hash'), ['payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_ingress_payloads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('raw_account_snapshots',
    sa.Column('ingress_payload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('margin', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('margin_free', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('margin_level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('trade_mode', sa.String(length=10), nullable=False),
    sa.Column('is_hedging', sa.Boolean(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingress_payload_id'], ['raw_ingress_payloads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_account_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_raw_snap_replay', ['tenant_id', 'account_number', 'snapshot_time_utc', 'received_at_utc', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_account_snapshots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_account_snapshots_ingress_payload_id'), ['ingress_payload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_account_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('raw_position_snapshots',
    sa.Column('ingress_payload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingress_payload_id'], ['raw_ingress_payloads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_position_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_raw_pos_replay', ['tenant_id', 'account_number', 'snapshot_time_utc', 'received_at_utc', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_position_snapshots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_position_snapshots_ingress_payload_id'), ['ingress_payload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_position_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sync_gap_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_sync_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('gap_classification', sa.String(length=32), nullable=False),
    sa.Column('anomaly_category', sa.String(length=64), nullable=False),
    sa.Column('evidence_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_sync_id'], ['account_sync_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_gap_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_gap_events_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_gap_events_account_sync_id'), ['account_sync_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_gap_events_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pairing_tokens', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('raw_event_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observation_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('ingress_payload_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('server_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('item_payload_hash', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('raw_item_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('observation_status', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('source_time_msc', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('source_timestamp_utc', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('received_at_utc', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('external_event_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_raw_event_observations_event_type'))
        batch_op.drop_index(batch_op.f('ix_raw_event_observations_external_event_id'))
        batch_op.drop_index(batch_op.f('ix_raw_event_observations_external_ticket'))
        batch_op.drop_index(batch_op.f('ix_raw_event_observations_received_at'))
        batch_op.drop_index(batch_op.f('ix_raw_obs_device_ticket'))
        batch_op.drop_index(batch_op.f('ix_raw_obs_tenant_event'))
        batch_op.create_index('idx_raw_obs_ext_id', ['tenant_id', 'account_number', 'event_type', 'external_ticket'], unique=False)
        batch_op.create_index('idx_raw_obs_replay_deal', ['tenant_id', 'account_number', 'source_time_msc', 'external_ticket', 'observation_id'], unique=False)
        batch_op.create_index('idx_raw_obs_replay_order', ['tenant_id', 'account_number', 'source_time_msc', 'external_ticket', 'observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_observations_ingress_payload_id'), ['ingress_payload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_observations_observation_id'), ['observation_id'], unique=True)
        batch_op.drop_column('payload')
        batch_op.drop_column('received_at')
        batch_op.drop_column('payload_hash')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('raw_event_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload_hash', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('received_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('payload', sqlite.JSON(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'devices', ['device_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_raw_event_observations_observation_id'))
        batch_op.drop_index(batch_op.f('ix_raw_event_observations_ingress_payload_id'))
        batch_op.drop_index('idx_raw_obs_replay_order')
        batch_op.drop_index('idx_raw_obs_replay_deal')
        batch_op.drop_index('idx_raw_obs_ext_id')
        batch_op.create_index(batch_op.f('ix_raw_obs_tenant_event'), ['tenant_id', 'external_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_obs_device_ticket'), ['device_id', 'external_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_observations_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_observations_external_ticket'), ['external_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_observations_external_event_id'), ['external_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_observations_event_type'), ['event_type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('external_event_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('event_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('source_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('received_at_utc')
        batch_op.drop_column('source_timestamp_utc')
        batch_op.drop_column('source_time_msc')
        batch_op.drop_column('observation_status')
        batch_op.drop_column('raw_item_json')
        batch_op.drop_column('item_payload_hash')
        batch_op.drop_column('server_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('ingress_payload_id')
        batch_op.drop_column('observation_id')

    with op.batch_alter_table('pairing_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('sync_gap_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_gap_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sync_gap_events_account_sync_id'))
        batch_op.drop_index(batch_op.f('ix_sync_gap_events_account_number'))

    op.drop_table('sync_gap_events')
    with op.batch_alter_table('raw_position_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_position_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_position_snapshots_ingress_payload_id'))
        batch_op.drop_index(batch_op.f('ix_raw_position_snapshots_device_id'))
        batch_op.drop_index('idx_raw_pos_replay')

    op.drop_table('raw_position_snapshots')
    with op.batch_alter_table('raw_account_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_account_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_account_snapshots_ingress_payload_id'))
        batch_op.drop_index(batch_op.f('ix_raw_account_snapshots_device_id'))
        batch_op.drop_index('idx_raw_snap_replay')

    op.drop_table('raw_account_snapshots')
    with op.batch_alter_table('raw_ingress_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_ingress_payloads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_ingress_payloads_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_ingress_payloads_device_id'))
        batch_op.drop_index(batch_op.f('ix_raw_ingress_payloads_account_number'))

    op.drop_table('raw_ingress_payloads')
    with op.batch_alter_table('account_sync_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_sync_states_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_account_sync_states_account_number'))
        batch_op.drop_index('idx_account_sync_lookup')

    op.drop_table('account_sync_states')
    # ### end Alembic commands ###
