"""phase5_canonical_ledger_and_trade_reconstruction

Revision ID: 2e9527af86b5
Revises: 2141b1a8b66a
Create Date: 2026-08-18 20:49:48.701883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9527af86b5'
down_revision: Union[str, None] = '2141b1a8b66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_exchange_rates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('effective_time_msc', sa.BigInteger(), nullable=False),
    sa.Column('effective_timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'base_currency', 'quote_currency', 'effective_time_msc', name='uq_hist_fx_rate')
    )
    with op.batch_alter_table('historical_exchange_rates', schema=None) as batch_op:
        batch_op.create_index('idx_hist_fx_lookup', ['tenant_id', 'base_currency', 'quote_currency', 'effective_time_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_exchange_rates_effective_time_msc'), ['effective_time_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_exchange_rates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('instrument_specifications',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('tick_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('profit_currency', sa.String(length=10), nullable=False),
    sa.Column('calculation_mode', sa.String(length=32), nullable=False),
    sa.Column('effective_from_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'symbol', 'effective_from_utc', name='uq_inst_spec_timeline')
    )
    with op.batch_alter_table('instrument_specifications', schema=None) as batch_op:
        batch_op.create_index('idx_inst_spec_lookup', ['tenant_id', 'symbol', 'effective_from_utc', 'effective_to_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_instrument_specifications_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_instrument_specifications_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('reconstruction_runs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_number', 'run_number', name='uq_recon_run_account_num')
    )
    with op.batch_alter_table('reconstruction_runs', schema=None) as batch_op:
        batch_op.create_index('idx_recon_runs_lookup', ['tenant_id', 'account_number', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstruction_runs_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstruction_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('canonical_trades',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reconstruction_run_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('account_mode', sa.String(length=16), nullable=False),
    sa.Column('position_ticket', sa.BigInteger(), nullable=False),
    sa.Column('total_entry_volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_exit_volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('open_volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vwap_entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('vwap_exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('realized_gross_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_swap', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_net_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('trade_status', sa.String(length=32), nullable=False),
    sa.Column('opened_at_msc', sa.BigInteger(), nullable=False),
    sa.Column('opened_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at_msc', sa.BigInteger(), nullable=True),
    sa.Column('closed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('supersedes_trade_id', sa.UUID(), nullable=True),
    sa.Column('superseded_by_trade_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['canonical_trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconstruction_run_id'], ['reconstruction_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_trade_id'], ['canonical_trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_trade_id'], ['canonical_trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_trades', schema=None) as batch_op:
        batch_op.create_index('idx_can_trades_lookup', ['reconstruction_run_id', 'account_number', 'symbol', 'trade_status'], unique=False)
        batch_op.create_index('idx_can_trades_time', ['reconstruction_run_id', 'account_number', 'opened_at_msc', 'closed_at_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trades_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trades_closed_at_msc'), ['closed_at_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trades_opened_at_msc'), ['opened_at_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trades_position_ticket'), ['position_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trades_reconstruction_run_id'), ['reconstruction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trades_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('canonical_balance_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reconstruction_run_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('ingress_payload_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('deal_ticket', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('event_time_msc', sa.BigInteger(), nullable=False),
    sa.Column('event_timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingress_payload_id'], ['raw_ingress_payloads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observation_id'], ['raw_event_observations.observation_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconstruction_run_id'], ['reconstruction_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconstruction_run_id', 'account_number', 'deal_ticket', name='uq_canonical_bal_run')
    )
    with op.batch_alter_table('canonical_balance_events', schema=None) as batch_op:
        batch_op.create_index('idx_can_bal_time', ['reconstruction_run_id', 'account_number', 'event_time_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_balance_events_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_balance_events_deal_ticket'), ['deal_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_balance_events_event_time_msc'), ['event_time_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_balance_events_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_balance_events_reconstruction_run_id'), ['reconstruction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_balance_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('canonical_executions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reconstruction_run_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('ingress_payload_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('matched_volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('deal_ticket', sa.BigInteger(), nullable=False),
    sa.Column('order_ticket', sa.BigInteger(), nullable=False),
    sa.Column('position_ticket', sa.BigInteger(), nullable=False),
    sa.Column('counter_position_ticket', sa.BigInteger(), nullable=True),
    sa.Column('counter_deal_ticket', sa.BigInteger(), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('swap', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('execution_time_msc', sa.BigInteger(), nullable=False),
    sa.Column('execution_timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingress_payload_id'], ['raw_ingress_payloads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observation_id'], ['raw_event_observations.observation_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconstruction_run_id'], ['reconstruction_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconstruction_run_id', 'account_number', 'deal_ticket', name='uq_canonical_exec_run')
    )
    with op.batch_alter_table('canonical_executions', schema=None) as batch_op:
        batch_op.create_index('idx_can_exec_pos_ticket', ['reconstruction_run_id', 'account_number', 'position_ticket'], unique=False)
        batch_op.create_index('idx_can_exec_replay', ['reconstruction_run_id', 'account_number', 'symbol', 'execution_time_msc', 'deal_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_deal_ticket'), ['deal_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_execution_time_msc'), ['execution_time_msc'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_position_ticket'), ['position_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_reconstruction_run_id'), ['reconstruction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_executions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('canonical_ledger_transactions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reconstruction_run_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('balance_event_id', sa.UUID(), nullable=True),
    sa.Column('source_observation_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('transaction_time_msc', sa.BigInteger(), nullable=False),
    sa.Column('transaction_timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['balance_event_id'], ['canonical_balance_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['canonical_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconstruction_run_id'], ['reconstruction_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['raw_event_observations.observation_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['canonical_trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_ledger_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_can_ledger_tx', ['reconstruction_run_id', 'account_number', 'transaction_time_msc', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_balance_event_id'), ['balance_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_reconstruction_run_id'), ['reconstruction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_source_observation_id'), ['source_observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_transactions_transaction_time_msc'), ['transaction_time_msc'], unique=False)

    op.create_table('canonical_trade_execution_map',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('entry_execution_id', sa.UUID(), nullable=False),
    sa.Column('exit_execution_id', sa.UUID(), nullable=True),
    sa.Column('matched_volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('realized_gross_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('attributed_commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('attributed_swap', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('attributed_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entry_execution_id'], ['canonical_executions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exit_execution_id'], ['canonical_executions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['canonical_trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_trade_execution_map', schema=None) as batch_op:
        batch_op.create_index('idx_map_entry_exec', ['entry_execution_id'], unique=False)
        batch_op.create_index('idx_map_exit_exec', ['exit_execution_id'], unique=False)
        batch_op.create_index('idx_map_trade_id', ['trade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trade_execution_map_entry_execution_id'), ['entry_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trade_execution_map_exit_execution_id'), ['exit_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_trade_execution_map_trade_id'), ['trade_id'], unique=False)

    op.create_table('canonical_ledger_postings',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)', name='chk_debit_or_credit'),
    sa.ForeignKeyConstraint(['transaction_id'], ['canonical_ledger_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_ledger_postings', schema=None) as batch_op:
        batch_op.create_index('idx_can_postings_tx', ['transaction_id', 'account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_ledger_postings_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('account_sync_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_reconstruction_run_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_account_sync_active_recon_run', 'reconstruction_runs', ['active_reconstruction_run_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    with op.batch_alter_table('account_sync_states', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_sync_active_recon_run', type_='foreignkey')
        batch_op.drop_column('active_reconstruction_run_id')

    op.drop_table('canonical_ledger_postings')
    op.drop_table('canonical_trade_execution_map')
    op.drop_table('canonical_ledger_transactions')
    op.drop_table('canonical_executions')
    op.drop_table('canonical_balance_events')
    op.drop_table('canonical_trades')
    op.drop_table('reconstruction_runs')
    op.drop_table('instrument_specifications')
    op.drop_table('historical_exchange_rates')
