"""phase3_devices_and_raw_events

Revision ID: ad084bfbed4b
Revises: eed7b6a01ed9
Create Date: 2026-08-18 20:08:28.128625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad084bfbed4b'
down_revision: Union[str, None] = 'eed7b6a01ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('device_secret', sa.String(length=64), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(length=100), nullable=False),
    sa.Column('trade_mode', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('terminal_build', sa.BigInteger(), nullable=False),
    sa.Column('connector_version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_time_msc', sa.BigInteger(), nullable=False),
    sa.Column('last_sync_deal_ticket', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_account_number'), 'devices', ['account_number'], unique=False)
    op.create_index('ix_devices_tenant_account', 'devices', ['tenant_id', 'account_number'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('pairing_tokens',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_tokens_tenant_id'), 'pairing_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pairing_tokens_token_hash'), 'pairing_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_pairing_tokens_user_id'), 'pairing_tokens', ['user_id'], unique=False)
    op.create_table('raw_event_observations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('external_ticket', sa.BigInteger(), nullable=False),
    sa.Column('external_event_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_event_observations_device_id'), 'raw_event_observations', ['device_id'], unique=False)
    op.create_index(op.f('ix_raw_event_observations_event_type'), 'raw_event_observations', ['event_type'], unique=False)
    op.create_index(op.f('ix_raw_event_observations_external_event_id'), 'raw_event_observations', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_raw_event_observations_external_ticket'), 'raw_event_observations', ['external_ticket'], unique=False)
    op.create_index(op.f('ix_raw_event_observations_received_at'), 'raw_event_observations', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_event_observations_tenant_id'), 'raw_event_observations', ['tenant_id'], unique=False)
    op.create_index('ix_raw_obs_device_ticket', 'raw_event_observations', ['device_id', 'external_ticket'], unique=False)
    op.create_index('ix_raw_obs_tenant_event', 'raw_event_observations', ['tenant_id', 'external_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_obs_tenant_event', table_name='raw_event_observations')
    op.drop_index('ix_raw_obs_device_ticket', table_name='raw_event_observations')
    op.drop_index(op.f('ix_raw_event_observations_tenant_id'), table_name='raw_event_observations')
    op.drop_index(op.f('ix_raw_event_observations_received_at'), table_name='raw_event_observations')
    op.drop_index(op.f('ix_raw_event_observations_external_ticket'), table_name='raw_event_observations')
    op.drop_index(op.f('ix_raw_event_observations_external_event_id'), table_name='raw_event_observations')
    op.drop_index(op.f('ix_raw_event_observations_event_type'), table_name='raw_event_observations')
    op.drop_index(op.f('ix_raw_event_observations_device_id'), table_name='raw_event_observations')
    op.drop_table('raw_event_observations')
    op.drop_index(op.f('ix_pairing_tokens_user_id'), table_name='pairing_tokens')
    op.drop_index(op.f('ix_pairing_tokens_token_hash'), table_name='pairing_tokens')
    op.drop_index(op.f('ix_pairing_tokens_tenant_id'), table_name='pairing_tokens')
    op.drop_table('pairing_tokens')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index('ix_devices_tenant_account', table_name='devices')
    op.drop_index(op.f('ix_devices_account_number'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
